version: "3.3"
services:
  app:
    env_file:
      -.env
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080" 
    networks:
      - mutants
networks:
  mutants: 